name: chemberta_upgraded_env
channels:
  - pytorch
  - rdkit
  - conda-forge
dependencies:
  - absl-py
  - cudatoolkit=10.1.243
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - nlp
  - optuna
  - pandas
  - pip
  - pre_commit
  - python=3.8
  - pytorch=1.9.0
  - rdkit
  - regex
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
  - tqdm
  - transformers
  - wandb
  - pip:
    - datasets
    - deepchem>=2.4.0rc1.dev20200916050731
    - simpletransformers
    - tensorflow>=2.0
