name: new_chemberta_env
channels:
  - conda-forge
  - anaconda
dependencies:
  - absl-py
  - nvidia::cudatoolkit
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pre_commit
  - pytorch::pytorch
  - python>=3.6
  - rdkit::rdkit
  - regex
  - s3fs
  - scikit-learn>=0.22
  - scipy>=1.3.1
  - seaborn
  - pytorch::torchvision
  - tqdm
  - pip:
    - datasets
    - deepchem>=2.4.0rc1.dev20200916050731
    - optuna
    - simpletransformers
    - tensorflow>=2.0
    - transformers
    - wandb

