name: chemberta_env
channels:
  - pytorch
  - huggingface
  - rdkit
  - conda-forge
dependencies:
  - absl-py
  - cudatoolkit
  - huggingface::datasets
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - nlp
  - optuna
  - pandas
  - pip
  - pre_commit
  - python
  - pytorch
  - rdkit
  - regex
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
  - tqdm
  - huggingface::transformers
  - wandb
  - pip:
    - deepchem>=2.4.0rc1.dev20200916050731
    - simpletransformers
    - tensorflow>=2.0
  
